name: Windows TensorFlow Java Native Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build TensorFlow Java Native (Windows)
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java & Maven
        shell: cmd
        run: |
          echo ===== Java & Maven Versions =====
          java -version
          mvn -version

      - name: Install Python + Git
        shell: cmd
        run: |
          choco install -y git python --no-progress
          python -m pip install numpy six wheel
          python --version
          git --version

      - name: Configure MSVC Build Environment
        shell: cmd
        run: |
          echo ===== Configuring MSVC =====
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cl

      - name: Prepare Environment for Bazel
        shell: cmd
        run: |
          echo ===== Preparing TMP & Bazel Env =====
          mkdir C:\tmp
          setx TMPDIR "C:\tmp"
          setx TEMP "C:\tmp"
          setx TMP "C:\tmp"
          setx TEST_TMPDIR "C:\tmp"

      - name: Force Bazel to use Java 17
        shell: cmd
        run: |
          echo ===== Forcing Bazel to use Java 17 =====
          setx BAZEL_JAVA_HOME "%JAVA_HOME%"
          setx JAVA_HOME "%JAVA_HOME%"
          java -version

      - name: Build TensorFlow Java Native (Bazel + Maven)
        shell: cmd
        run: |
          echo ===== Building TensorFlow Java Native (Windows) =====
          call mvn clean install ^
            -Pnative-build ^
            -Pwindows ^
            -B -U -e ^
            -Djavacpp.cppbuild=true ^
            -Djavacpp.platform=windows-x86_64 ^
            -Dmaven.test.skip=true ^
            -DskipTests=true ^
            -Djavacpp.platform.custom=windows-x86_64
          if ERRORLEVEL 1 exit /b 1

      - name: Verify Artifacts
        shell: cmd
        run: |
          echo ===== Build Artifacts =====
          dir tensorflow-core\tensorflow-core-api\target
          dir tensorflow-core\tensorflow-core-native\target

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflow-java-native-windows
          path: |
            tensorflow-core/**/*.jar
            tensorflow-core/**/*.dll
            tensorflow-core/**/*.pdb
