name: Windows TensorFlow Java Native Build

on:
  workflow_dispatch:  # manual trigger

jobs:
  build-windows:
    name: Build TensorFlow Java Native (Windows)
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Force Java 17 for all tools
        shell: cmd
        run: |
          echo Forcing JAVA_HOME and PATH
          setx JAVA_HOME "%JAVA_HOME%"
          setx PATH "%JAVA_HOME%\bin;%PATH%"
          java -version
          mvn -version

      - name: Install Dependencies
        shell: cmd
        run: |
          choco install -y git python --no-progress
          python -m pip install numpy six wheel
          python --version
          git --version

      - name: Configure MSVC Compiler
        shell: cmd
        run: |
          echo Configuring MSVC environment
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cl

      - name: Prepare TMP & Bazel Environment
        shell: cmd
        run: |
          echo ===== Preparing TMP & Bazel Env =====
          mkdir C:\tmp
          setx TMPDIR "C:\tmp"
          setx TEMP "C:\tmp"
          setx TMP "C:\tmp"
          setx TEST_TMPDIR "C:\tmp"

      - name: Force Bazel to Use Java 17
        shell: cmd
        run: |
          echo ===== Forcing Bazel to Java 17 =====
          setx BAZEL_JAVA_HOME "%JAVA_HOME%"
          setx JAVA_HOME "%JAVA_HOME%"
          java -version

      - name: Check Bazel Environment
        shell: cmd
        run: |
          echo ===== Bazel Info =====
          bazel version
          bazel info java-home

      - name: Build TensorFlow Java Native (Windows)
        shell: cmd
        run: |
          echo ===== Starting Native Build =====
          call mvn clean install ^
            -Pnative-build ^
            -Pwindows ^
            -B -U -e ^
            -Djavacpp.cppbuild=true ^
            -Djavacpp.platform=windows-x86_64 ^
            -Djavacpp.platform.custom=windows-x86_64 ^
            -Dmaven.test.skip=true ^
            -DskipTests=true
          if ERRORLEVEL 1 exit /b 1

      - name: Verify Build Artifacts
        shell: cmd
        run: |
          echo ===== Build Artifacts =====
          dir tensorflow-core\tensorflow-core-api\target
          dir tensorflow-core\tensorflow-core-native\target
          dir tensorflow-core\tensorflow-core-native\target\native

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflow-java-native-windows
          path: |
            tensorflow-core/**/*.jar
            tensorflow-core/**/*.dll
            tensorflow-core/**/*.pdb
