name: Build TensorFlow Java (No AVX, Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      - name: Install prerequisites
        run: |
          choco install python --version=3.10.11 -y
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools" -y
          choco install msys2 -y
          echo "PATH=C:\\msys64\\usr\\bin;$env:PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify environment
        run: |
          python --version
          javac -version
          bazel version

      - name: Build TensorFlow Java (no AVX)
        shell: pwsh
        run: |
          echo "Starting TensorFlow Java build without AVX..."
          mvn clean install -Pnative-build -Pwindows -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflow-java-noavx
          path: |
            tensorflow/java/target/*.jar
            tensorflow/java/native/target/*.dll
