name: Windows TensorFlow Java Native Build

on:
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  build-windows:
    name: Build TensorFlow Java (Native + Maven)
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Force Java 17 on PATH
        shell: cmd
        run: |
          echo ====== Forcing Java 17 ======
          setx JAVA_HOME "%JAVA_HOME%"
          setx PATH "%JAVA_HOME%\bin;%PATH%"
          java -version

      - name: Install Dependencies
        shell: cmd
        run: |
          echo Installing Python + tools...
          choco install -y git python --no-progress
          python -m pip install numpy six wheel
          git --version
          python --version

      - name: Configure MSVC Compiler
        shell: cmd
        run: |
          echo Setting up MSVC environment...
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cl

      - name: Verify Java Version (again)
        shell: cmd
        run: |
          echo Java version check:
          java -version
          echo Maven version check:
          mvn -version

      - name: Build TensorFlow Java + Native
        shell: cmd
        run: |
          echo ====== Preparing Build Environment ======
          set "PATH=C:\msys64\usr\bin;%PATH%"
          mkdir C:\tmp
          set "TMPDIR=C:\tmp"
          set "TEMP=C:\tmp"
          set "TMP=C:\tmp"
          set "TEST_TMPDIR=C:\tmp"

          echo ====== Building TensorFlow Java Native ======
          call mvn clean install ^
            -Pjdk17 ^
            -Pnative ^
            -B -U -e ^
            -Djavacpp.cppbuild=true ^
            -Djavacpp.platform=windows-x86_64 ^
            -Dmaven.test.skip=true ^
            -DskipTests=true ^
            -Djavacpp.platform.custom=windows-x86_64
          if ERRORLEVEL 1 exit /b 1

      - name: Verify Artifacts
        shell: cmd
        run: |
          echo ====== Build Artifacts ======
          dir tensorflow-core\tensorflow-core-api\target
          dir tensorflow-core\tensorflow-core-native\target

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflow-java-native-windows
          path: |
            tensorflow-core/**/*.jar
            tensorflow-core/**/*.dll
            tensorflow-core/**/*.pdb
