name: Windows TensorFlow Java Native Build

on:
  workflow_dispatch:  # manual trigger

jobs:
  build-windows:
    name: Build TensorFlow Java Native (Windows)
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: 'tensorflow/java'
          ref: 'v1.0.0'

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Force Java 17 for all tools
        shell: cmd
        run: |
          echo Forcing JAVA_HOME and PATH
          set JAVA_HOME=%JAVA_HOME%
          set PATH=%JAVA_HOME%\bin;%PATH%
          java -version
          mvn -version

      - name: Install Python 3.12 and TensorFlow Dependencies
        shell: cmd
        run: |
          echo ===== Installing Python 3.12 =====
          choco install -y python --version=3.12.0 --force
          set PATH=C:\Python312;C:\Python312\Scripts;%PATH%
          python --version
          pip3 install -U pip
          pip3 install -U six numpy wheel packaging
          pip3 install -U keras_preprocessing --no-deps

      - name: Install MSYS2 and Dependencies
        shell: cmd
        run: |
          echo ===== Installing MSYS2 =====
          choco install -y msys2
          set PATH=C:\msys64\usr\bin;%PATH%
          C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
          C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm git patch unzip rsync"

      - name: Install Visual C++ Build Tools 2022
        shell: cmd
        run: |
          echo ===== Visual C++ Build Tools already available in runner =====
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cl

      - name: Install Bazel 6.5.0
        shell: cmd
        run: |
          echo ===== Installing Bazel 6.5.0 =====
          mkdir C:\bazel
          curl -Lo C:\bazel\bazel.exe https://github.com/bazelbuild/bazel/releases/download/6.5.0/bazel-6.5.0-windows-x86_64.exe
          set PATH=C:\bazel;%PATH%
          bazel --version

      - name: Setup Environment Variables
        shell: cmd
        run: |
          echo ===== Setting Environment Variables =====
          set PATH=C:\Python312;C:\Python312\Scripts;%PATH%
          set PYTHON_BIN_PATH=C:\Python312\python.exe
          set PYTHON_LIB_PATH=C:\Python312\Lib\site-packages
          set PYTHON_DIRECTORY=C:\Python312\Scripts
          set BAZEL_SH=C:\msys64\usr\bin\bash.exe
          set BAZEL_VS=C:\Program Files\Microsoft Visual Studio\2022\Enterprise
          set BAZEL_VC=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC
          echo Environment variables set:
          echo PYTHON_BIN_PATH=%PYTHON_BIN_PATH%
          echo BAZEL_SH=%BAZEL_SH%
          echo BAZEL_VC=%BAZEL_VC%

      - name: Force Bazel to Use Java 17
        shell: cmd
        run: |
          echo ===== Forcing Bazel to Java 17 =====
          set BAZEL_JAVA_HOME=%JAVA_HOME%
          set JAVA_HOME=%JAVA_HOME%
          java -version
          echo Bazel Java home will be set during build

      - name: Prepare TMP Environment
        shell: cmd
        run: |
          echo ===== Preparing TMP Env =====
          mkdir C:\tmp
          set TMPDIR=C:\tmp
          set TEMP=C:\tmp
          set TMP=C:\tmp
          set TEST_TMPDIR=C:\tmp

      - name: Build TensorFlow Java Native (Windows)
        shell: cmd
        run: |
          echo ===== Starting Native Build =====
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          set BAZEL_JAVA_HOME=%JAVA_HOME%
          set BAZEL_SH=%BAZEL_SH%
          set BAZEL_VC=%BAZEL_VC%
          set TMPDIR=C:\tmp
          set TEMP=C:\tmp
          set TMP=C:\tmp
          set TEST_TMPDIR=C:\tmp
          call mvn clean package ^
            -Pnative-build ^
            -Pwindows ^
            -B -U -e ^
            -Djavacpp.cppbuild=true ^
            -Djavacpp.platform=windows-x86_64 ^
            -Djavacpp.platform.custom=windows-x86_64 ^
            -Dbazel.executable=C:\bazel\bazel.exe ^
            -DskipTests=true
          if ERRORLEVEL 1 exit /b 1

      - name: Verify Build Artifacts
        shell: cmd
        run: |
          echo ===== Build Artifacts =====
          dir tensorflow-core\tensorflow-core-api\target
          dir tensorflow-core\tensorflow-core-native\target
          dir tensorflow-core\tensorflow-core-native\target\native

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflow-java-native-windows
          path: |
            tensorflow-core/**/*.jar
            tensorflow-core/**/*.dll
            tensorflow-core/**/*.pdb
