name: Windows TensorFlow Java Native Build

on:
  workflow_dispatch:  # manual trigger

jobs:
  build-windows:
    name: Build TensorFlow Java Native (Windows)
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Force Java 17 for all tools
        shell: cmd
        run: |
          echo Forcing JAVA_HOME and PATH
          setx JAVA_HOME "%JAVA_HOME%"
          setx PATH "%JAVA_HOME%\bin;%PATH%"
          java -version
          mvn -version

      - name: Install Dependencies (Python 3.12 + Git)
        shell: cmd
        run: |
          echo Installing Python 3.12 and Git
          choco install -y python --version=3.12.0 git --no-progress
          python --version
          git --version
          python -m pip install numpy six wheel

      - name: Configure MSVC Compiler
        shell: cmd
        run: |
          echo Configuring MSVC environment
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cl

      - name: Prepare TMP & Bazel Environment
        shell: cmd
        run: |
          echo ===== Preparing TMP & Bazel Env =====
          mkdir C:\tmp
          setx TMPDIR "C:\tmp"
          setx TEMP "C:\tmp"
          setx TMP "C:\tmp"
          setx TEST_TMPDIR "C:\tmp"

      - name: Install Bazel 6.5.0
        shell: cmd
        run: |
          echo ===== Installing Bazel 6.5.0 =====
          curl -Lo C:\bazel-6.5.0-windows-x86_64.exe https://github.com/bazelbuild/bazel/releases/download/6.5.0/bazel-6.5.0-windows-x86_64.exe
          setx PATH "C:\;%PATH%"
          echo Bazel version:
          C:\bazel-6.5.0-windows-x86_64.exe --version

      - name: Force Bazel to Use Java 17
        shell: cmd
        run: |
          echo ===== Forcing Bazel to Java 17 =====
          setx BAZEL_JAVA_HOME "%JAVA_HOME%"
          setx JAVA_HOME "%JAVA_HOME%"
          java -version

      - name: Check Bazel Environment
        shell: cmd
        run: |
          echo ===== Bazel Info =====
          C:\bazel-6.5.0-windows-x86_64.exe info java-home

      - name: Build TensorFlow Java Native (Windows)
        shell: cmd
        run: |
          echo ===== Starting Native Build =====
          call mvn clean install ^
            -Pnative-build ^
            -Pwindows ^
            -B -U -e ^
            -Djavacpp.cppbuild=true ^
            -Djavacpp.platform=windows-x86_64 ^
            -Djavacpp.platform.custom=windows-x86_64 ^
            -Dbazel.executable=C:\bazel-6.5.0-windows-x86_64.exe ^
            -Dmaven.test.skip=true ^
            -DskipTests=true
          if ERRORLEVEL 1 exit /b 1

      - name: Verify Build Artifacts
        shell: cmd
        run: |
          echo ===== Build Artifacts =====
          dir tensorflow-core\tensorflow-core-api\target
          dir tensorflow-core\tensorflow-core-native\target
          dir tensorflow-core\tensorflow-core-native\target\native

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflow-java-native-windows
          path: |
            tensorflow-core/**/*.jar
            tensorflow-core/**/*.dll
            tensorflow-core/**/*.pdb
